name: Docker

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

env:
  # renovate: datasource=docker depName=ghcr.io/usa-reddragon/trunk-recorder-prometheus
  PROMETHEUS_BASE_IMAGE_TAG: main@sha256:afe700092fe5f916d186ffec9b6c523ff15e1a941344989a5bd7150ae79b68b7

jobs:
  base:
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@v1.0.5
    with:
      push: ${{ github.event_name != 'pull_request' }}

  prometheus:
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@v1.0.5
    with:
      push: ${{ github.event_name != 'pull_request' }}
      image-name: ${{ github.repository }}-prometheus
      build-args: |
        BASE_IMAGE=ghcr.io/usa-reddragon/trunk-recorder-prometheus:${{ env.PROMETHEUS_BASE_IMAGE_TAG }}
