name: Docker

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*']

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

env:
  # renovate: datasource=docker depName=ghcr.io/usa-reddragon/trunk-recorder-prometheus
  PROMETHEUS_BASE_IMAGE_TAG: main@sha256:afe700092fe5f916d186ffec9b6c523ff15e1a941344989a5bd7150ae79b68b7

jobs:
  base:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@v1.2.0
    with:
      push: ${{ github.event_name != 'pull_request' }}
      security-category: base

  vars:
    runs-on: ubuntu-22.04
    outputs:
      base_image_tag: ${{ env.PROMETHEUS_BASE_IMAGE_TAG }}
    steps:
      - run: echo "Exposing env vars"

  prometheus:
    needs: [vars]
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/docker-ci.yaml@v1.2.0
    with:
      push: ${{ github.event_name != 'pull_request' }}
      image-name: ${{ github.repository }}-prometheus
      build-args: |
        BASE_IMAGE=ghcr.io/usa-reddragon/trunk-recorder-prometheus:${{ needs.vars.outputs.base_image_tag }}
      security-category: prometheus
